### ISSUE TITLE
MFA doesn't work

### ISSUE THREAD

**Issue by fliker09** [sekai-soft/nitter#7]
Tried to use TWITTER_MFA_CODE and got this:

> web    | Started with pid 19...
> web    | Running auth...
> web    | DEBUG:root:TW_ANDROID_BASIC_TOKEN=Basic M25WdVNvQlpueDZVNHZ6VXhmNXc6QmNzNTlFRmJic2RGNlNsOU5nNzFzbWdTdFdFR3dYWEtTall2UFZ0N3F5cw==
> web    | DEBUG:root:start authenticating @test_account
> web    | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com:443
> web    | DEBUG:urllib3.connectionpool:https://api.twitter.com:443 "POST /oauth2/token HTTP/11" 200 152
> web    | DEBUG:root:bearer_token=bearer AAAAAAAAAAAAAAAAAAAAAFXzAwAAAAAAMHCxpeSDG1gLNLghVe8d74hl6k4%3DRUMF4xAQLsbeBhTSRrCiQpJtxoGWeyHrDb5te2jpGskWDFW82F
> web    | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com:443
> web    | DEBUG:urllib3.connectionpool:https://api.twitter.com:443 "POST /1.1/guest/activate.json HTTP/11" 200 63
> web    | DEBUG:root:guest_token=1859331147974500446
> web    | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com:443
> web    | DEBUG:urllib3.connectionpool:https://api.twitter.com:443 "POST /1.1/onboarding/task.json?flow_name=login&api_version=1&known_device_token=&sim_country_code=us HTTP/11" 200 550
> web    | DEBUG:root:task1 res={'flow_token': 'g;173213406515849789:-1732134065170:JzCKwSp4YLs1BcjDu1XWACni:0', 'status': 'success', 'subtasks': [{'subtask_id': 'LoginEnterUserIdentifier', 'enter_text': {'primary_text': {'text': 'To get started, first enter your phone, email, or @username', 'entities': []}, 'hint_text': 'Phone, email, or username', 'multiline': False, 'auto_capitalization_type': 'none', 'auto_correction_enabled': False, 'os_content_type': 'username', 'keyboard_type': 'text', 'next_link': {'link_type': 'task', 'link_id': 'next_link', 'label': 'Next'}, 'skip_link': {'link_type': 'subtask', 'link_id': 'forget_password', 'label': 'Forgot password?', 'subtask_id': 'RedirectToPasswordReset'}}, 'subtask_back_navigation': 'cancel_flow'}, {'subtask_id': 'RedirectToPasswordReset', 'open_link': {'link': {'link_type': 'deep_link_and_abort', 'link_id': 'password_reset_deep_link', 'url': 'twitter://onboarding/task?flow_name=password_reset&input_flow_data=%7B%22requested_variant%22%3A%22eyJwbGF0Zm9ybSI6IkFuZHJvaWQifQ%3D%3D%22%7D'}}}]}
> web    | DEBUG:urllib3.connectionpool:https://api.twitter.com:443 "POST /1.1/onboarding/task.json HTTP/11" 200 532
> web    | DEBUG:root:task2 res={'flow_token': 'g;173213406515849789:-1732134065170:JzCKwSp4YLs1BcjDu1XWACni:6', 'status': 'success', 'subtasks': [{'subtask_id': 'LoginEnterPassword', 'enter_password': {'primary_text': {'text': 'Enter your password', 'entities': []}, 'next_link': {'link_type': 'task', 'link_id': 'next_link', 'label': 'Log in'}, 'hint': 'Password', 'username': 'test_account', 'user_identifier_display_type': 'username', 'skip_link': {'link_type': 'subtask', 'link_id': 'forget_password', 'label': 'Forgot password?', 'subtask_id': 'RedirectToPasswordReset'}, 'skip_password_validation': True, 'os_content_type': 'password'}, 'subtask_back_navigation': 'cancel_flow'}, {'subtask_id': 'RedirectToPasswordReset', 'open_link': {'link': {'link_type': 'deep_link_and_abort', 'link_id': 'password_reset_deep_link', 'url': 'twitter://onboarding/task?flow_name=password_reset&input_flow_data=%7B%22requested_variant%22%3A%22eyJ1c2VyX2lkZW50aWZpZXIiOiJleHRvbGVkZXYyIiwicGxhdGZvcm0iOiJBbmRyb2lkIn0%3D%22%7D'}}}]}
> web    | DEBUG:urllib3.connectionpool:https://api.twitter.com:443 "POST /1.1/onboarding/task.json HTTP/11" 200 1277
> web    | DEBUG:root:task3 res={'flow_token': 'g;173213406515849789:-1732134065170:JzCKwSp4YLs1BcjDu1XWACni:8', 'status': 'success', 'subtasks': [{'subtask_id': 'LoginTwoFactorAuthChallenge', 'enter_text': {'header': {'primary_text': {'text': 'Enter your verification code', 'entities': []}, 'secondary_text': {'text': 'Use your code generator app to generate a code and enter it below.', 'entities': []}, 'user': {'id': 2883940153, 'id_str': '2883940153', 'name': 'test_account', 'screen_name': 'test_account', 'location': 'San Francisco, CA', 'url': None, 'description': None, 'protected': False, 'followers_count': -1, 'friends_count': -1, 'listed_count': None, 'created_at': 'Thu Oct 30 21:38:27 +0000 2014', 'favourites_count': -1, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': -1, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1003629168465252354/_bKAlHX8_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1003629168465252354/_bKAlHX8_normal.jpg', 'profile_link_color': '', 'profile_sidebar_border_color': '', 'profile_sidebar_fill_color': '', 'profile_text_color': '', 'profile_use_background_image': False, 'default_profile': True, 'default_profile_image': False, 'can_media_tag': None, 'following': None, 'follow_request_sent': None, 'notifications': None, 'muting': None, 'blocking': None, 'blocked_by': None, 'translator_type': 'none', 'withheld_in_countries': [], 'followed_by': None}}, 'detail_text': {'text': 'Choose a different verification method\n\nContact X Support', 'entities': [{'from_index': 0, 'to_index': 38, 'navigation_link': {'link_type': 'subtask', 'link_id': 'choose_different_method', 'label': 'choose_methods_link', 'subtask_id': 'LoginTwoFactorAuthChooseMethod'}}, {'from_index': 40, 'to_index': 57, 'navigation_link': {'link_type': 'chromeless_web_link', 'link_id': 'login_issues_link', 'url': 'https://help.twitter.com/forms/account-access/regain-access'}}]}, 'hint_text': 'Enter code', 'multiline': False, 'auto_capitalization_type': 'none', 'auto_correction_enabled': False, 'keyboard_type': 'number', 'next_link': {'link_type': 'task', 'link_id': 'next_link', 'label': 'Next'}}, 'subtask_back_navigation': 'cancel_flow'}, {'subtask_id': 'LoginTwoFactorAuthChooseMethod', 'choice_selection': {'selection_type': 'single_select', 'choices': [{'id': '0', 'text': {'text': 'Use a code generator app', 'entities': []}}, {'id': '1', 'text': {'text': 'Use a backup code', 'entities': []}}], 'primary_text': {'text': 'Choose a different verification method', 'entities': []}, 'next_link': {'link_type': 'task', 'link_id': 'next_link', 'label': 'Next'}, 'style': 'default', 'sections': []}, 'subtask_back_navigation': 'cancel_flow'}, {'subtask_id': 'login_security_key_not_supported_cta', 'cta': {'header': {'primary_text': {'text': 'Why can’t you log in using a security key?', 'entities': []}, 'secondary_text': {'text': "You can log in to twitter.com with a security key only when using a compatible web browser. Currently, the X mobile app doesn't support the use of security keys. ", 'entities': []}}, 'primary_action_link': {'link_type': 'subtask', 'link_id': 'choose_different_method', 'label': 'Next', 'subtask_id': 'LoginTwoFactorAuthChooseMethod'}, 'text_alignment': 'left', 'primary_action_style': 'primary', 'secondary_action_style': 'secondary', 'style': 'scrollable'}}]}
> web    | Requested 'Enter code'
> web    | DEBUG:urllib3.connectionpool:https://api.twitter.com:443 "POST /1.1/onboarding/task.json HTTP/11" 400 91
> web    | Failed authentication for any account. Did you enter the right username/password? Please rerun with environment variable DEBUG=1 for debugging, e.g. uncomment the DEBUG=1 in docker-compose.yml file.

I am sure of my timing, but no dice. Would appreciate any hints on what's wrong.

**Comment by inbev92** [comment]
have same problem with flyio or docker.

**Comment by stephenreid321** [comment]
I'm also having problems with MFA.

Could we make it work with a cookie string instead like https://github.com/vladkens/twscrape/tree/main ?

**Comment by KTachibanaM** [comment]
I added logging for task4, and you should be able to see more detailed error messages if you update the docker image

@stephenreid321 It's technically possible, but Nitter doesn't work with cookies, and I don't have enough experience with the codebase or the Nim language to add it unfortunately.

**Comment by ronaldho** [comment]
I think the extra logging is causing the app to crash actually...

``` 
web    | DEBUG:urllib3.connectionpool:https://api.twitter.com:443 "POST /1.1/onboarding/task.json HTTP/1.1" 400 155
web    | Traceback (most recent call last):
web    |   File "/src/scripts/auth.py", line 216, in <module>
web    |     auth_result = auth(username, password, mfa_code)
web    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web    |   File "/src/scripts/auth.py", line 143, in auth
web    |     logging.debug("task4 res=" + str(task4.json()))
web    |                                      ^^^^^^^^^^
web    | AttributeError: 'dict' object has no attribute 'json'
web    | Exited with code 1
nginx  | Interrupting...
nginx  | Exited with code 0

```

I'm not sure if I am doing something wrong, but I can't get it to boot up properly.

My `twitter-credentials.json` has `username`, `password`, and `mfa_code`

After the first failed login, I quickly grab the mfa_code from my email, then bring docker down and up again, but I see that in my logs
